[versions]
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"

bettercommand = "1.4.3"
betterhud = "1.14.1"
bettermodel = "2.1.0"
coreprotect = "23.1"
entitylib = "3.0.3-SNAPSHOT"
exposed = "1.0.0"
hikaricp = "7.0.2"
jnoise = "4.1.0"
kaml = "0.104.0"
koin = "4.1.1"
mccoroutine = "2.22.0"
minecraftexposed = "1.0.0-R0.1-SNAPSHOT"
minecraftserialization = "1.0.0-R0.6-SNAPSHOT"
packed = "1.0.0-R0.5-SNAPSHOT"
packetevents = "2.11.2"
paperweight = "2.0.0-beta.19"
postgresql = "42.7.10"
shadow = "9.3.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
paperweight-patcher = { id = "io.papermc.paperweight.patcher", version.ref = "paperweight" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
# Language
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }

# Dependency Injection (DI)
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Minecraft
bettercommand = { module = "io.github.toxicity188:BetterCommand", version.ref = "bettercommand" }
betterhud-bukkit-api = { module = "io.github.toxicity188:BetterHud-bukkit-api", version.ref = "betterhud" }
betterhud-standard-api = { module = "io.github.toxicity188:BetterHud-standard-api", version.ref = "betterhud" }
bettermodel-bukkit-api = { module = "io.github.toxicity188:bettermodel-bukkit-api", version.ref = "bettermodel" }
coreprotect = { module = "net.coreprotect:coreprotect", version.ref = "coreprotect" }
entitylib = { module = "io.github.tofaa2:spigot", version.ref = "entitylib" }
mccoroutine-folia-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-api", version.ref = "mccoroutine" }
mccoroutine-folia-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-core", version.ref = "mccoroutine" }
minecraftexposed-adventure = { module = "net.azisaba.exposed:adventure", version.ref = "minecraftexposed" }
minecraftserialization-adventure = { module = "net.azisaba.serialization:adventure", version.ref = "minecraftserialization" }
minecraftserialization-joml = { module = "net.azisaba.serialization:joml", version.ref = "minecraftserialization" }
minecraftserialization-valueproviders = { module = "net.azisaba.serialization:value-providers", version.ref = "minecraftserialization" }
packed-core = { module = "net.azisaba.packed:core", version.ref = "packed" }
packed-resource = { module = "net.azisaba.packed:resource", version.ref = "packed" }
packed-server = { module = "net.azisaba.packed:server", version.ref = "packed" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }

# Database
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Utility
jnoise-pipeline = { module = "de.articdive:jnoise-pipeline", version.ref = "jnoise" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
